# -*- coding: utf-8 -*-
"""Logistic_Regression(Iris)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWP5WHM8-r44pToKrhIEsmwLWKFcULRi
"""

import seaborn as sns
import pandas as pd
import numpy as np
df= sns.load_dataset('iris')
df.head()

df['species'].unique()  # multi class classification

df.isnull().sum()

df=df[df['species']!='setosa']  # binary classification

df.head()

df['species']=df['species'].map({'versicolor':0,'virginica':1})

df.head()

X=df.iloc[:,:-1]
y=df.iloc[:,-1]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42)

from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()

from sklearn.model_selection import GridSearchCV
parameter={'penalty':['l1','l2','elasticnet'],'C':[1,2,3,4,5,6,10.20,30,40,50],'max_iter':[100,200,300]}

classifier_regressor=GridSearchCV(classifier,param_grid=parameter,scoring='accuracy',cv=5)

classifier_regressor.fit(X_train,y_train)

print(classifier_regressor.best_params_)

print(classifier_regressor.best_score_)

## prediction
y_pred=classifier_regressor.predict(X_test)

### score
from sklearn.metrics import accuracy_score, classification_report
score=accuracy_score(y_test,y_pred)
print(score)

print(classification_report(y_test,y_pred))

sns.pairplot(df,hue='species')

df.corr()

